apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingprocessor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bookingprocessor
  template:
    metadata:
      labels:
        app: bookingprocessor
    spec:
      containers:
        - name: bookingprocessor
          image: dn010590sas/bookingprocessor:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"
            - name: DB_MAX_CONNECTIONS
              value: "{{ .Values.env.DB_MAX_CONNECTIONS }}"
            - name: MAX_PODS
              value: "{{ .Values.env.MAX_PODS }}"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{.Values.resources.limits.cpu}}
              memory: {{.Values.resources.limits.memory}}
