apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: bookingprocessor
spec:
  selector:
    matchLabels:
      app: bookingprocessor
  endpoints:
    - port: http
      path: /metrics
      interval: 30s