apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingprocessor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookingprocessor
  template:
    metadata:
      labels:
        app: bookingprocessor
    spec:
      containers:
        - name: bookingprocessor
          image: dn010590sas/bookingprocessor:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: "postgres://testuser:testpass@postgres:5432/testdb?sslmode=disable"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
