apiVersion: v1
kind: Service
metadata:
  name: citus-coordinator
  labels:
    app: {{ include "citus.name" . }}
    role: coordinator
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
{{/*      name: postgres*/}}
  selector:
    app: {{ include "citus.name" . }}
    role: coordinator