apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "citus.fullname" . }}-postgres-config
data:
  postgresql.conf: |
    wal_level = logical
    max_replication_slots = 10
    max_wal_senders     = 10