# templates/worker-headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "citus.fullname" . }}-worker
  labels:
    app: {{ include "citus.name" . }}
    role: worker
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{ include "citus.name" . }}
    role: worker
