apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-worker
  labels:
    app: citus
    role: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: citus
      role: worker
  template:
    metadata:
      labels:
        app: citus
        role: worker
    spec:
      containers:
        - name: citus-worker
          image: citusdata/citus:13.0
          imagePullPolicy: IfNotPresent
          args:
            - "-c"
            - "wal_level=logical"
            - "-c"
            - "max_replication_slots=10"
            - "-c"
            - "max_wal_senders=10"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "mypass"
            - name: CITUS_ROLE
              value: "worker"
            - name: CITUS_COORDINATOR_HOST
              value: "{{ include "citus.fullname" . }}-coordinator"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}