replicaCount: 3
image:
  repository: dn010590sas/bookingprocessor
  tag: latest

resources:
  requests:
    cpu: "0.5"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

hpa:
  minReplicas: 10
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30

env:
  DATABASE_URL: "postgres://testuser:testpass@postgres:5432/testdb?sslmode=disable"
  DB_MAX_CONNECTIONS: "100"
  MAX_PODS: "10"

prometheus:
  serviceMonitor:
    enabled: true

postgres:
  enabled: true
  replicaCount: 1
  image:
    repository: postgres
    tag: "13"
  username: "testuser"
  password: "testpass"
  database: "testdb"
  port: 5432
  resources:
    requests:
      cpu: "0.5"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
