replicaCount: 2
image:
  repository: dn010590sas/bookingprocessor
  tag: latest

resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "2Gi"

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30

env:
  DATABASE_URL: "postgres://postgres:mypass@citus-coordinator:5432/postgres?sslmode=disable"
  DB_MAX_CONNECTIONS: "100"
  MAX_PODS: "5"

prometheus:
  serviceMonitor:
    enabled: true

postgres:
  enabled: true
  replicaCount: 1
  image:
    repository: postgres
    tag: "13"
  username: "testuser"
  password: "testpass"
  database: "testdb"
  port: 5432
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
